### ISSUE TITLE
don't need to await login?

### ISSUE THREAD

**Issue by kbyatnal** [jkettmann/graphql-passport#42]
In the getting started guide, we have

```
      // only required if express-session is used
      context.login(user);
```

Shouldn't this be `await context.login(user)`?

**Comment by gforge** [comment]
Not sure about that, my feeling is that the async is within the authenticate action where the login just moves the user into the express-session - the login function is defined in Passport.

**Comment by feute** [comment]
`login` is a promise and can be `await`able, yes. But, as @gforge said:

> the login just moves the user into the express-session

Since `login` doesn't return any relevant data to the client (it's defined as a `Promise<void>`), it can be called without `await` and it will save the session "in the background." And of course, it could be called with `await` and use `try`/`catch` to ensure the session is saved and handle errors in the process.

**Comment by jkettmann** [comment]
The answers here are correct. Just for completion here is the documentation for the corresponding [login function in passport](http://www.passportjs.org/docs/login/). It says

> When the login operation completes, user will be assigned to req.user.

This means you only need to call `login` and wait for it if you want to use `req.user` anywhere afterward. If the login mutation is the only thing that is done and you simply return the `user` object from the resolver you might not even need to call it.
